import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const ENV_PATH = process.env.YTVB_ENV || 'C:/Users/nz_jo/AppData/Local/hermes/profiles/axomega-biz-bot/.env';
const OUT_PATH = path.resolve(import.meta.dirname, '../src/config.local.js');

const text = await readFile(ENV_PATH, 'utf8');
// Only an UNCOMMENTED assignment counts.
const match = text.match(/^\s*OPENROUTER_API_KEY\s*=\s*"?([^"#\r\n]+)"?\s*$/m);
if (!match) {
  console.error(`No uncommented OPENROUTER_API_KEY found in ${ENV_PATH}`);
  console.error('Fall back to pasting the key into the extension options page.');
  process.exit(1);
}
const key = match[1].trim();
await writeFile(
  OUT_PATH,
  '// GENERATED by tools/set-key.mjs. Gitignored. Dev-only fallback for chrome.storage.apiKey.\n' +
    `export const DEV_API_KEY = ${JSON.stringify(key)};\n`,
);
console.log(`wrote ${OUT_PATH}`);
console.log(`key length ${key.length}, prefix ${key.slice(0, 8)}... (value never printed in full)`);
console.log('This file feeds the Node tools only (npm run smoke / npm run e2e).');
console.log('The extension itself reads chrome.storage.local - set the key in its Options page.');
